image: node:18-buster

cache:
  paths:
    - node_modules/

stages:
  - install
  - build

install:
  stage: install
  script:
    # Install npm dependencies
    - npm install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    # Run the Vite build
    - npm run build
  artifacts:
    paths:
      - public/

# Deploy to GitLab Pages
pages:
  stage: deploy
  script:
    # Create the .public directory and move the build output there
    - mkdir .public
    - cp -r public/* .public
  artifacts:
    paths:
      - .public
  only:
    - dev
