# The Docker image that will be used to build your app
image: node:18-buster

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: production

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public/

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r public/* .public
  artifacts:
    paths:
      - .public
  only:
    - dev  # Jalankan hanya pada branch main (ubah sesuai kebutuhan)
