image: node:18-buster

# Cache untuk mempercepat pipeline
cache:
  paths:
    - node_modules/
    - vendor/

stages:
  - install
  - build
  - deploy

# Instalasi dependencies (PHP dan Node.js)
install_dependencies:
  stage: install
  script:
    # Instal PHP dan extensions yang dibutuhkan oleh Laravel
    - apt-get update && apt-get install -y php php-cli php-xml php-mbstring php-zip php-curl

    # Instal Composer
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    # Instal dependencies Laravel menggunakan Composer
    - composer install --prefer-dist --no-dev --no-ansi --no-interaction --no-progress --optimize-autoloader

    # Instal dependencies Node.js menggunakan npm
    - npm install
  artifacts:
    paths:
      - vendor/
      - node_modules/

# Build frontend menggunakan Vite
build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - public/

# Deploy ke GitLab Pages (Opsional)
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r public/* .public
  artifacts:
    paths:
      - .public
  only:
    - dev
