image: php:8.2-fpm-alpine

cache:
  paths:
    - vendor/
    - node_modules/

stages:
  - install
  - build
  - deploy

install_dependencies:
  stage: install
  script:
    # Install Node.js (karena image ini hanya memiliki PHP)
    - apk add --no-cache nodejs npm

    # Install PHP extension exif
    - apk add --no-cache php8-exif

    # Verifikasi versi PHP dan Node.js
    - php -v
    - node -v
    - npm -v

    # Instal dependencies Laravel menggunakan Composer
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --prefer-dist --no-dev --no-ansi --no-interaction --no-progress --optimize-autoloader

    # Instal dependencies frontend menggunakan npm
    - npm install
  artifacts:
    paths:
      - vendor/
      - node_modules/

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - public/

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r public/* .public
  artifacts:
    paths:
      - .public
  only:
    - dev
