# Menggunakan image Docker dengan PHP 8.2 dan Node.js
image: edbizarro/laravel-ci:node-18

# Cache untuk dependencies
cache:
  paths:
    - vendor/
    - node_modules/

stages:
  - install
  - build
  - deploy

# Job untuk instalasi dependencies
install_dependencies:
  stage: install
  script:
    # Instal dependencies Laravel menggunakan Composer
    - composer install --prefer-dist --no-dev --no-ansi --no-interaction --no-progress --optimize-autoloader

    # Instal dependencies Node.js menggunakan npm
    - npm install
  artifacts:
    paths:
      - vendor/
      - node_modules/

# Job untuk membangun frontend menggunakan Vite
build:
  stage: build
  script:
    # Build Vite
    - npm run build
  artifacts:
    paths:
      - public/

# Job untuk deploy ke GitLab Pages (opsional)
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r public/* .public
  artifacts:
    paths:
      - .public
  only:
    - dev
